name: Release

on:
  push:
    tags:
      - "*.*.*"

jobs:
  release:
    name: Push release to CocoaPods Trunk

    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Push to CocoaPods Trunk
        run: pod trunk push
